#flags and compiler
CC=g++
C=gcc
FLAGS=-wall -wextra -g -std=c++11

#source file and output
 SRC1=setCount.cpp
 OUT1=setCount
 SRC2=stupid2.cpp
 OUT2=stupid2
 SRC3=x1.c
 OUT3=x1
#targets
$(OUT1):$(SRC1)
	$(CC) $(SRC1) -o $(OUT1)

$(OUT2):$(SRC2)
	$(CC) $(SRC2) -o $(OUT2)

$(OUT3):$(SRC3)
	$(C) $(SRC3) -o $(SRC3)


#run targets  
run1:$(OUT1)
	./$(OUT1)
   
run2:$(out2)
	 ./$(out2)

#clean built file   
clean:
	rm -f $(OUT1)
	rm -f $(OUT2)

